#!/bin/bash
set -e

echo "set_real_ip_from 10.0.0.0/8;" > /etc/nginx/conf.d/aws.conf
for SUBNET in $(curl 'https://ip-ranges.amazonaws.com/ip-ranges.json' | jq -r '.prefixes[] | select(.service=="CLOUDFRONT") | .ip_prefix'); do
        echo "set_real_ip_from $SUBNET;" >> /etc/nginx/conf.d/aws.conf
done
echo "real_ip_header X-Forwarded-For;" >> /etc/nginx/conf.d/aws.conf
echo "real_ip_recursive on;" >> /etc/nginx/conf.d/aws.conf

nginx -t > /dev/null 2>&1
if [ $? -gt 0 ]; then
        echo "error generating aws config"
        exit 1
fi
systemctl reload nginx
